# player_schema = {
#     "season": {
#         "name": "season",
#         "type": "object",
#         "fields": [
#             "ab",
#             "avg",
#             "babip",
#             "bb%",
#             "gp",
#             "hbp",
#             "hr/fb",
#             "iso",
#             "k",
#             "k%",
#             "muwoba",
#             "obp",
#             "ops",
#             "sb",
#             "slg",
#             "wellhitpct",
#             "woba",
#             "xwoba",
#         ]
#     },
#     "last-two": {
#         "name": "last-two",
#         "type": "object",
#         "fields": [
#             "ab",
#             "avg",
#             "babip",
#             "bb%",
#             "gp",
#             "hbp",
#             "hr/fb",
#             "iso",
#             "k",
#             "k%",
#             "muwoba",
#             "obp",
#             "ops",
#             "sb",
#             "slg",
#             "wellhitpct",
#             "woba",
#             "xwoba",
#         ]
#     },
#     "yesterday": {
#         "name": "yesterday",
#         "type": "object",
#         "fields": [
#             "ab",
#             "avg",
#             "babip",
#             "bb%",
#             "gp",
#             "hbp",
#             "hr/fb",
#             "iso",
#             "k",
#             "k%",
#             "muwoba",
#             "obp",
#             "ops",
#             "sb",
#             "slg",
#             "wellhitpct",
#             "woba",
#             "xwoba",
#         ]
#     },
#     "1week": {
#         "name": "1week",
#         "type": "object",
#         "fields": [
#             "ab",
#             "avg",
#             "babip",
#             "bb%",
#             "gp",
#             "hbp",
#             "hr/fb",
#             "iso",
#             "k",
#             "k%",
#             "muwoba",
#             "obp",
#             "ops",
#             "sb",
#             "slg",
#             "wellhitpct",
#             "woba",
#             "xwoba",
#         ]
#     },
#     "2week": {
#         "name": "2week",
#         "type": "object",
#         "fields": [
#             "ab",
#             "avg",
#             "babip",
#             "bb%",
#             "gp",
#             "hbp",
#             "hr/fb",
#             "iso",
#             "k",
#             "k%",
#             "muwoba",
#             "obp",
#             "ops",
#             "sb",
#             "slg",
#             "wellhitpct",
#             "woba",
#             "xwoba",
#         ]
#     },
#     "4week": {
#         "name": "yesterday",
#         "type": "object",
#         "fields": [
#             "ab",
#             "avg",
#             "babip",
#             "bb%",
#             "gp",
#             "hbp",
#             "hr/fb",
#             "iso",
#             "k",
#             "k%",
#             "muwoba",
#             "obp",
#             "ops",
#             "sb",
#             "slg",
#             "wellhitpct",
#             "woba",
#             "xwoba",
#         ]
#     },
#     "12week": {
#         "name": "yesterday",
#         "type": "object",
#         "fields": [
#             "ab",
#             "avg",
#             "babip",
#             "bb%",
#             "gp",
#             "hbp",
#             "hr/fb",
#             "iso",
#             "k",
#             "k%",
#             "muwoba",
#             "obp",
#             "ops",
#             "sb",
#             "slg",
#             "wellhitpct",
#             "woba",
#             "xwoba",
#         ]
#     },
#     "player": {
#         "name": "player",
#         "type": "object",
#         "fields": [
#             "first_name",
#             "hand",
#             "id",
#             "last_name",
#             "position",
#             # "salaries",
#             "sport",
#             "team",
#             "team_id",
#         ]
#     },
#     "player_name": {
#         "name": "player_name",
#         "type": "string"
#     },
#     "salary": {
#         "name": "salary"
#     },
#     "import_data": {
#         "name": "import_data"
#     },
#     "fpts": {
#         "name": "fpts"
#     },
#     "player_id": {
#         "name": "player_id"
#     },
#     "position": {
#         "name": "position"
#     },
#     "salary": {
#         "name": "salary"
#     },
#     "slate_id": {
#         "name": "slate_id",
#         "type": "list"
#     },
#     "type": {
#         "name": "type"
#     },
#     "schedule_id": {
#         "name": "schedule_id"
#     },
#     "team": {
#         "name": "team"
#     },
#     "home?": {
#         "name": "home?"
#     },
#     "position": {
#         "name": "position"
#     },
#     "opp": {
#         "name": "opp"
#     },
#     "dvp": {
#         "name": "dvp"
#     },
#     "dvprank": {
#         "name": "dvprank"
#     },
#     "projected_stats_id": {
#         "name": "projected_stats_id"
#     },
#     "deviation": {
#         "name": "deviation"
#     },
#     "pmin": {
#         "name": "pmin"
#     },
#     "ceil": {
#         "name": "ceil"
#     },
#     "floor": {
#         "name": "floor"
#     },
#     "points": {
#         "name": "points"
#     },
#     "pown%": {
#         "name": "pown%"
#     },
#     "rank": {
#         "name": "pown%"
#     },
#     "saldiff": {
#         "name": "saldiff"
#     },
#     "rankdiff": {
#         "name": "rankdiff"
#     },
#     "average": {
#         "name": "average"
#     },
#     "pt/$/k": {
#         "name": "pt/$/k"
#     },
#     "contr": {
#         "name": "contr"
#     },
#     "id": {
#         "name": "id"
#     },
#     "player_id": {
#         "name": "player_id"
#     },
#     "status": {
#         "name": "status"
#     },
#     "ceiling": {
#         "name": "ceiling"
#     },
#     "minutes": {
#         "name": "minutes"
#     },
#     "ip": {
#         "name": "ip"
#     },
#     "schedule": {
#         "name": "schedule"
#     },
#     "o/u": {
#         "name": "o/u"
#     },
#     "total": {
#         "name": "total"
#     },
#     "line": {
#         "name": "line"
#     },
#     "movement": {
#         "name": "movement"
#     },
#     "props": {
#         "name": "props",
#         "type": "object",
#         "fields": [
#             "hits",
#             "home_runs",
#         ]
#     },
#     "pitcher": {
#         "name": "pitcher",
#         "type": "object",
#         "fields": [
#             "first_name",
#             "last_name",
#             "hand",
#             "id",
#         ]
#     },
#     "order": {
#         "name": "order",
#     },
#     "confirmed": {
#         "name": "confirmed",
#     },
#     "description": {
#         "name": "description",
#     },
#     "color": {
#         "name": "color",
#     },
#     "ump": {
#         "name": "ump",
#     },
#     "rating": {
#         "name": "rating",
#     },
#     "k_perc": {
#         "name": "k_perc",
#     },
#     "uibb_perc": {
#         "name": "uibb_perc",
#     },
#     "score": {
#         "name": "score",
#         "type": "object",
#         "fields": [
#             "contact",
#             "context",
#             "pitchtypes",
#             "production",
#             "platediscipline",
#             "recentskill",
#             "stolenbase",
#             "sbfactor",
#             "overall",
#         ]
#     },
#     "factors": {
#         "name": "factors",
#         "type": "object",
#         "fields": [
#             # "positive",
#             # "negative",
#             "name",
#             "type",
#             "description",
#             "comparisonValue",
#             "positivevect",
#             "negativevect",
#         ]
#     }
# }

#!/usr/bin/python
# -*- coding: utf-8 -*-

player_schema = {
    'last-two__xwoba': '0.157',
    'last-two__wellhitpct': '0',
    'last-two__obp': '0.067',
    'last-two__ops': '0.134',
    'last-two__slg': '0.067',
    'last-two__hbp': '0',
    'last-two__hr/fb': '0',
    'last-two__k': '4',
    'last-two__sb': '0',
    'last-two__gp': '9',
    'last-two__ab': '15',
    'last-two__woba': '0.059',
    'last-two__iso': '0',
    'last-two__babip': '0.091',
    'last-two__avg': '0.067',
    'last-two__k%': '26.7',
    'last-two__bb%': '0.0',
    'last-two__muwoba': '0.177',
    'season__xwoba': '0.157',
    'season__wellhitpct': '0',
    'season__obp': '0.067',
    'season__ops': '0.134',
    'season__slg': '0.067',
    'season__hbp': '0',
    'season__hr/fb': '0',
    'season__k': '4',
    'season__sb': '0',
    'season__gp': '9',
    'season__ab': '15',
    'season__woba': '0.059',
    'season__iso': '0',
    'season__babip': '0.091',
    'season__avg': '0.067',
    'season__k%': '26.7',
    'season__bb%': '0.0',
    'season__muwoba': '0.177',
    '12weeks__xwoba': '0.157',
    '12weeks__wellhitpct': '0',
    '12weeks__obp': '0.067',
    '12weeks__ops': '0.134',
    '12weeks__slg': '0.067',
    '12weeks__hbp': '0',
    '12weeks__hr/fb': '0',
    '12weeks__k': '4',
    '12weeks__sb': '0',
    '12weeks__gp': '9',
    '12weeks__ab': '15',
    '12weeks__woba': '0.059',
    '12weeks__iso': '0',
    '12weeks__babip': '0.091',
    '12weeks__avg': '0.067',
    '12weeks__k%': '26.7',
    '12weeks__bb%': '0.0',
    '12weeks__muwoba': '0.177',
    '4weeks__xwoba': '0.061',
    '4weeks__wellhitpct': '0',
    '4weeks__obp': '0.000',
    '4weeks__ops': '0.000',
    '4weeks__slg': '0.000',
    '4weeks__hbp': '0',
    '4weeks__hr/fb': '0',
    '4weeks__k': '1',
    '4weeks__sb': '0',
    '4weeks__gp': '3',
    '4weeks__ab': '7',
    '4weeks__woba': '0',
    '4weeks__iso': '0',
    '4weeks__babip': '0',
    '4weeks__avg': '0.000',
    '4weeks__k%': '14.3',
    '4weeks__bb%': '0.0',
    '4weeks__muwoba': '0.177',
    '2weeks__xwoba': '0.06',
    '2weeks__wellhitpct': '0',
    '2weeks__obp': '0.000',
    '2weeks__ops': '0.000',
    '2weeks__slg': '0.000',
    '2weeks__hbp': '0',
    '2weeks__hr/fb': '0',
    '2weeks__k': '0',
    '2weeks__sb': '0',
    '2weeks__gp': '1',
    '2weeks__ab': '1',
    '2weeks__woba': '0',
    '2weeks__iso': '0',
    '2weeks__babip': '0',
    '2weeks__avg': '0.000',
    '2weeks__k%': '0.0',
    '2weeks__bb%': '0.0',
    '2weeks__muwoba': '0.177',
    '1week__xwoba': '0.06',
    '1week__wellhitpct': '0',
    '1week__obp': '0.000',
    '1week__ops': '0.000',
    '1week__slg': '0.000',
    '1week__hbp': '0',
    '1week__hr/fb': '0',
    '1week__k': '0',
    '1week__sb': '0',
    '1week__gp': '1',
    '1week__ab': '1',
    '1week__woba': '0',
    '1week__iso': '0',
    '1week__babip': '0',
    '1week__avg': '0.000',
    '1week__k%': '0.0',
    '1week__bb%': '0.0',
    '1week__muwoba': '0.177',
    'yesterday__muwoba': '0.177',
    'yesterday__ab': '0',
    'yesterday__avg': '0',
    'yesterday__woba': '0',
    'yesterday__iso': '0',
    'yesterday__obp': '0',
    'yesterday__slg': '0',
    'yesterday__k%': '0',
    'yesterday__bb%': '0',
    'yesterday__ops': '0',
    'yesterday__babip': '0',
    'player__id': 814187,
    'player__xml_id': 'c7ac64c2-a5ef-4074-987f-45047b96dbfb',
    'player__first_name': 'Braden',
    'player__last_name': 'Bishop',
    'player__team': 'NA',
    'player__team_id': 105,
    'player__sport_id': 2,
    'player__hand': 'R',
    'player__position': 'OF',
    'player__salaries': 'NA',
    'player_name': 'Braden Bishop',
    'salary': '2300.00',
    'schedule_id': 56756,
    'team': 'SEA',
    'home?': True,
    'position': 'OF',
    'opp': 'HOU',
    'dvp': 0,
    'dvprank': 0,
    'projected_stats_id': 719017,
    'deviation': None,
    'pmin': None,
    'ceil': 10.93355,
    'floor': 0.0067700000000004,
    'points': 6.77,
    'pown%': '1.00%',
    'rank': None,
    'saldiff': 300,
    'rankdiff': -12,
    'average': None,
    'pt/$/k': 2.94,
    'contr': 6.77,
    'id': 719017,
    'player_id': 814187,
    'status': None,
    'ceiling': 0.615,
    'minutes': None,
    'ip': None,
    '2': 8.83,
    '20': 6.77,
    '43': 6.77,
    '50': 6.71,
    'schedule__data': 'NA',
    '60': 7.22,
    'o/u': 9.5,
    'total': 4.14,
    'line': 148,
    'movement': -0.04,
    'pitcher__last_name': 'Miley',
    'pitcher__first_name': 'Wade',
    'pitcher__hand': 'L',
    'pitcher__id': 11462,
    'order': 1,
    'confirmed': 1,
    'ump': 'Brian Knight',
    'rating': 'Hitters',
    'k_perc': '0.22',
    'uibb_perc': '0.09',
    'score__contact': 49.282761125,
    'score__context': 54.042,
    'score__pitchtypes': 55.080329086976,
    'score__production': 54.808255,
    'score__platediscipline': 49.342943,
    'score__recentskill': 38.58854485,
    'score__stolenbase': 22.3195,
    'score__sbfactor': 0.5579875,
    'score__overall': 51.2,
    'factors__positivect': 3,
    'factors__negativect': 11,
}

player_headers = [
    'last-two__xwoba',
    'last-two__wellhitpct',
    'last-two__obp',
    'last-two__ops',
    'last-two__slg',
    'last-two__hbp',
    'last-two__hr/fb',
    'last-two__k',
    'last-two__sb',
    'last-two__gp',
    'last-two__ab',
    'last-two__woba',
    'last-two__iso',
    'last-two__babip',
    'last-two__avg',
    'last-two__k%',
    'last-two__bb%',
    'last-two__muwoba',
    'season__xwoba',
    'season__wellhitpct',
    'season__obp',
    'season__ops',
    'season__slg',
    'season__hbp',
    'season__hr/fb',
    'season__k',
    'season__sb',
    'season__gp',
    'season__ab',
    'season__woba',
    'season__iso',
    'season__babip',
    'season__avg',
    'season__k%',
    'season__bb%',
    'season__muwoba',
    '12weeks__xwoba',
    '12weeks__wellhitpct',
    '12weeks__obp',
    '12weeks__ops',
    '12weeks__slg',
    '12weeks__hbp',
    '12weeks__hr/fb',
    '12weeks__k',
    '12weeks__sb',
    '12weeks__gp',
    '12weeks__ab',
    '12weeks__woba',
    '12weeks__iso',
    '12weeks__babip',
    '12weeks__avg',
    '12weeks__k%',
    '12weeks__bb%',
    '12weeks__muwoba',
    '4weeks__xwoba',
    '4weeks__wellhitpct',
    '4weeks__obp',
    '4weeks__ops',
    '4weeks__slg',
    '4weeks__hbp',
    '4weeks__hr/fb',
    '4weeks__k',
    '4weeks__sb',
    '4weeks__gp',
    '4weeks__ab',
    '4weeks__woba',
    '4weeks__iso',
    '4weeks__babip',
    '4weeks__avg',
    '4weeks__k%',
    '4weeks__bb%',
    '4weeks__muwoba',
    '2weeks__xwoba',
    '2weeks__wellhitpct',
    '2weeks__obp',
    '2weeks__ops',
    '2weeks__slg',
    '2weeks__hbp',
    '2weeks__hr/fb',
    '2weeks__k',
    '2weeks__sb',
    '2weeks__gp',
    '2weeks__ab',
    '2weeks__woba',
    '2weeks__iso',
    '2weeks__babip',
    '2weeks__avg',
    '2weeks__k%',
    '2weeks__bb%',
    '2weeks__muwoba',
    '1week__xwoba',
    '1week__wellhitpct',
    '1week__obp',
    '1week__ops',
    '1week__slg',
    '1week__hbp',
    '1week__hr/fb',
    '1week__k',
    '1week__sb',
    '1week__gp',
    '1week__ab',
    '1week__woba',
    '1week__iso',
    '1week__babip',
    '1week__avg',
    '1week__k%',
    '1week__bb%',
    '1week__muwoba',
    'yesterday__muwoba',
    'yesterday__ab',
    'yesterday__avg',
    'yesterday__woba',
    'yesterday__iso',
    'yesterday__obp',
    'yesterday__slg',
    'yesterday__k%',
    'yesterday__bb%',
    'yesterday__ops',
    'yesterday__babip',
    'player__id',
    'player__xml_id',
    'player__first_name',
    'player__last_name',
    'player__team',
    'player__team_id',
    'player__sport_id',
    'player__hand',
    'player__position',
    'player__salaries',
    'player_name',
    'salary',
    'schedule_id',
    'team',
    'home?',
    'position',
    'opp',
    'dvp',
    'dvprank',
    'projected_stats_id',
    'deviation',
    'pmin',
    'ceil',
    'floor',
    'points',
    'pown%',
    'rank',
    'saldiff',
    'rankdiff',
    'average',
    'pt/$/k',
    'contr',
    'id',
    'player_id',
    'status',
    'ceiling',
    'minutes',
    'ip',
    '2',
    '20',
    '43',
    '50',
    'schedule__data',
    '60',
    'o/u',
    'total',
    'line',
    'movement',
    'pitcher__last_name',
    'pitcher__first_name',
    'pitcher__hand',
    'pitcher__id',
    'order',
    'confirmed',
    'ump',
    'rating',
    'k_perc',
    'uibb_perc',
    'score__contact',
    'score__context',
    'score__pitchtypes',
    'score__production',
    'score__platediscipline',
    'score__recentskill',
    'score__stolenbase',
    'score__sbfactor',
    'score__overall',
    'factors__positivect',
    'factors__negativect',
]
